src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $message;

    #[ORM\Column(type: 'datetime')]
    private $date;

    #[ORM\Column(type: 'boolean')]
    private $is_Read;

    #[ORM\Column(type: 'integer')]
    private $sender;

    #[ORM\Column(type: 'integer')]
    private $reciver;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_Read;
    }

    public function setIsRead(bool $is_Read): self
    {
        $this->is_Read = $is_Read;

        return $this;
    }

    public function getSender(): ?int
    {
        return $this->sender;
    }

    public function setSender(int $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getReciver(): ?int
    {
        return $this->reciver;
    }

    public function setReciver(int $reciver): self
    {
        $this->reciver = $reciver;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

}

src/Controller/OutboxController.php
<?php

namespace App\Controller;

use App\Repository\MessageRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

//outbox controller to show all the messages that the user has sent

class OutboxController extends AbstractController
{
    #[Route('/outbox', name: 'outbox')]
    public function index(MessageRepository $messageRepository, UserRepository $userRepository): Response
    {

        //we call the entity user to get the user that it is logged
        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        //we get all the users in order to know who has sent us the email
        $allUsers = $userRepository->findAll();

        //Query to get the messages sent
        $messages = $messageRepository->createQueryBuilder('u')
            ->andWhere('u.sender = :val')
            ->setParameter('val', $user->getId())
            ->orderBy('u.date', 'DESC')
            ->getQuery()
            ->getResult();

        //we render the information to print it on the twig template
        return $this->render('outbox/index.html.twig', [
            'outbox_message' => $messages,
            'users' => $allUsers
        ]);
    }
}

templates/outbox/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Outbox
{% endblock %}

{% block body %}

	{# navbar with all the links to the other pages #}
	<nav class="navbar navbar-dark bg-dark d-flex justify-content-center">
		<a href=" {{ path('inbox') }} " class="btn btn-outline-info ms-3">Inbox</a>
		<a href=" {{ path('send_message') }} " class="btn btn-outline-success ms-3">Send Message</a>
		<a href=" {{ path('profile') }} " class="btn btn-outline-warning ms-3">Profile</a>
		<a href=" {{ path('app_logout') }} " class="btn btn-outline-danger ms-3">Logout</a>
	</nav>

	<div class="d-flex flex-column justify-content-center align-items-center mt-2">
		<h1>Outbox</h1>

		{# for each message we show the information from the controller #}
		{% for message in outbox_message %}

			<div class="card mb-2" style="width: 18rem;">
				<div class="card-body">

					{% for user in users %}
						{% if user.id == message.reciver %}
							{# If the user id is equal to the reciver id we show the email of the reciver #}
							<h6 class="card-title">{{ user.email }}</h6>
						{% endif %}
					{% endfor %}

					{# We show the message that we have sent #}
					<p class="card-text">{{ message.message }}</p>

					{% if message.isRead == 0 %}
						<i class="fas fa-envelope"></i>
					{% else %}
						<i class="fas fa-envelope-open"></i>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}